#!/bin/bash
#
APP_NAME=upload-data
USER=pi


function start ( )
{
	echo  "$APP_NAME: starting service"
	python /home/$USER/HomeWeather/readTemp.py $1 $2 $3 & echo $! >>/tmp/$APP_NAME.pid
	echo  "PID is $(cat /tmp/$APP_NAME.pid)"
}

function stop ( )
{
	echo  "$APP_NAME: stopping Service (PID = $(cat /tmp/$APP_NAME.pid) )"
	kill $(cat  /tmp/$APP_NAME.pid )
	rm  /tmp/$APP_NAME.pid
 }

function status ( )
{
	ps  -A | grep $(cat /tmp/$APP_NAME.pid)
	echo  "PID = $(cat /tmp/$APP_NAME.pid)"
}

case "$1" in
    'start')
            start $2 $3 $4
            ;;
    'stop')
            stop
            ;;
    'restart')
            stop ; echo "Sleeping..."; sleep 1 ;
            start
            ;;
    'status')
            status
            ;;
    *)
            echo
            echo "Usage: $0 { start | stop | restart | status }"
            echo
            exit 1
            ;;
esac

exit 0
